services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${PORT_POSTGRES}:5432"

  odoo:
    image: odoo:17.0
    restart: always
    depends_on:
      - db
    ports:
      - "${PORT_ODOO}:8069"
    environment:
      - HOST=${POSTGRES_HOST}
      - PORT=${POSTGRES_PORT}
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    command: ["odoo", "-i", "base", "-d", "${POSTGRES_DB}"]
    volumes:
      - ./odoo_data:/var/lib/odoo

  n8n:
    image: n8nio/n8n:latest
    restart: always
    depends_on:
      - db
    ports:
      - "${PORT_N8N}:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./n8n_data:/home/node/.n8n